// Code generated by ent, DO NOT EDIT.

package agentskillrepo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldName, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldScopeID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldCreatedBy, v))
}

// GithubURL applies equality check predicate on the "github_url" field. It's identical to GithubURLEQ.
func GithubURL(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldGithubURL, v))
}

// RefValue applies equality check predicate on the "ref_value" field. It's identical to RefValueEQ.
func RefValue(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldRefValue, v))
}

// LastUploadFilename applies equality check predicate on the "last_upload_filename" field. It's identical to LastUploadFilenameEQ.
func LastUploadFilename(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldLastUploadFilename, v))
}

// LastUploadAt applies equality check predicate on the "last_upload_at" field. It's identical to LastUploadAtEQ.
func LastUploadAt(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldLastUploadAt, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldIsDeleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContainsFold(FieldName, v))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v ScopeType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v ScopeType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...ScopeType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...ScopeType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContainsFold(FieldScopeID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldCreatedBy, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldSourceType, vs...))
}

// GithubURLEQ applies the EQ predicate on the "github_url" field.
func GithubURLEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldGithubURL, v))
}

// GithubURLNEQ applies the NEQ predicate on the "github_url" field.
func GithubURLNEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldGithubURL, v))
}

// GithubURLIn applies the In predicate on the "github_url" field.
func GithubURLIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldGithubURL, vs...))
}

// GithubURLNotIn applies the NotIn predicate on the "github_url" field.
func GithubURLNotIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldGithubURL, vs...))
}

// GithubURLGT applies the GT predicate on the "github_url" field.
func GithubURLGT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldGithubURL, v))
}

// GithubURLGTE applies the GTE predicate on the "github_url" field.
func GithubURLGTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldGithubURL, v))
}

// GithubURLLT applies the LT predicate on the "github_url" field.
func GithubURLLT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldGithubURL, v))
}

// GithubURLLTE applies the LTE predicate on the "github_url" field.
func GithubURLLTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldGithubURL, v))
}

// GithubURLContains applies the Contains predicate on the "github_url" field.
func GithubURLContains(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContains(FieldGithubURL, v))
}

// GithubURLHasPrefix applies the HasPrefix predicate on the "github_url" field.
func GithubURLHasPrefix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasPrefix(FieldGithubURL, v))
}

// GithubURLHasSuffix applies the HasSuffix predicate on the "github_url" field.
func GithubURLHasSuffix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasSuffix(FieldGithubURL, v))
}

// GithubURLIsNil applies the IsNil predicate on the "github_url" field.
func GithubURLIsNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIsNull(FieldGithubURL))
}

// GithubURLNotNil applies the NotNil predicate on the "github_url" field.
func GithubURLNotNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotNull(FieldGithubURL))
}

// GithubURLEqualFold applies the EqualFold predicate on the "github_url" field.
func GithubURLEqualFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEqualFold(FieldGithubURL, v))
}

// GithubURLContainsFold applies the ContainsFold predicate on the "github_url" field.
func GithubURLContainsFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContainsFold(FieldGithubURL, v))
}

// RefTypeEQ applies the EQ predicate on the "ref_type" field.
func RefTypeEQ(v RefType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldRefType, v))
}

// RefTypeNEQ applies the NEQ predicate on the "ref_type" field.
func RefTypeNEQ(v RefType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldRefType, v))
}

// RefTypeIn applies the In predicate on the "ref_type" field.
func RefTypeIn(vs ...RefType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldRefType, vs...))
}

// RefTypeNotIn applies the NotIn predicate on the "ref_type" field.
func RefTypeNotIn(vs ...RefType) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldRefType, vs...))
}

// RefTypeIsNil applies the IsNil predicate on the "ref_type" field.
func RefTypeIsNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIsNull(FieldRefType))
}

// RefTypeNotNil applies the NotNil predicate on the "ref_type" field.
func RefTypeNotNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotNull(FieldRefType))
}

// RefValueEQ applies the EQ predicate on the "ref_value" field.
func RefValueEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldRefValue, v))
}

// RefValueNEQ applies the NEQ predicate on the "ref_value" field.
func RefValueNEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldRefValue, v))
}

// RefValueIn applies the In predicate on the "ref_value" field.
func RefValueIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldRefValue, vs...))
}

// RefValueNotIn applies the NotIn predicate on the "ref_value" field.
func RefValueNotIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldRefValue, vs...))
}

// RefValueGT applies the GT predicate on the "ref_value" field.
func RefValueGT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldRefValue, v))
}

// RefValueGTE applies the GTE predicate on the "ref_value" field.
func RefValueGTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldRefValue, v))
}

// RefValueLT applies the LT predicate on the "ref_value" field.
func RefValueLT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldRefValue, v))
}

// RefValueLTE applies the LTE predicate on the "ref_value" field.
func RefValueLTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldRefValue, v))
}

// RefValueContains applies the Contains predicate on the "ref_value" field.
func RefValueContains(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContains(FieldRefValue, v))
}

// RefValueHasPrefix applies the HasPrefix predicate on the "ref_value" field.
func RefValueHasPrefix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasPrefix(FieldRefValue, v))
}

// RefValueHasSuffix applies the HasSuffix predicate on the "ref_value" field.
func RefValueHasSuffix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasSuffix(FieldRefValue, v))
}

// RefValueIsNil applies the IsNil predicate on the "ref_value" field.
func RefValueIsNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIsNull(FieldRefValue))
}

// RefValueNotNil applies the NotNil predicate on the "ref_value" field.
func RefValueNotNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotNull(FieldRefValue))
}

// RefValueEqualFold applies the EqualFold predicate on the "ref_value" field.
func RefValueEqualFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEqualFold(FieldRefValue, v))
}

// RefValueContainsFold applies the ContainsFold predicate on the "ref_value" field.
func RefValueContainsFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContainsFold(FieldRefValue, v))
}

// LastUploadFilenameEQ applies the EQ predicate on the "last_upload_filename" field.
func LastUploadFilenameEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldLastUploadFilename, v))
}

// LastUploadFilenameNEQ applies the NEQ predicate on the "last_upload_filename" field.
func LastUploadFilenameNEQ(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldLastUploadFilename, v))
}

// LastUploadFilenameIn applies the In predicate on the "last_upload_filename" field.
func LastUploadFilenameIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldLastUploadFilename, vs...))
}

// LastUploadFilenameNotIn applies the NotIn predicate on the "last_upload_filename" field.
func LastUploadFilenameNotIn(vs ...string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldLastUploadFilename, vs...))
}

// LastUploadFilenameGT applies the GT predicate on the "last_upload_filename" field.
func LastUploadFilenameGT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldLastUploadFilename, v))
}

// LastUploadFilenameGTE applies the GTE predicate on the "last_upload_filename" field.
func LastUploadFilenameGTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldLastUploadFilename, v))
}

// LastUploadFilenameLT applies the LT predicate on the "last_upload_filename" field.
func LastUploadFilenameLT(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldLastUploadFilename, v))
}

// LastUploadFilenameLTE applies the LTE predicate on the "last_upload_filename" field.
func LastUploadFilenameLTE(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldLastUploadFilename, v))
}

// LastUploadFilenameContains applies the Contains predicate on the "last_upload_filename" field.
func LastUploadFilenameContains(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContains(FieldLastUploadFilename, v))
}

// LastUploadFilenameHasPrefix applies the HasPrefix predicate on the "last_upload_filename" field.
func LastUploadFilenameHasPrefix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasPrefix(FieldLastUploadFilename, v))
}

// LastUploadFilenameHasSuffix applies the HasSuffix predicate on the "last_upload_filename" field.
func LastUploadFilenameHasSuffix(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldHasSuffix(FieldLastUploadFilename, v))
}

// LastUploadFilenameIsNil applies the IsNil predicate on the "last_upload_filename" field.
func LastUploadFilenameIsNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIsNull(FieldLastUploadFilename))
}

// LastUploadFilenameNotNil applies the NotNil predicate on the "last_upload_filename" field.
func LastUploadFilenameNotNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotNull(FieldLastUploadFilename))
}

// LastUploadFilenameEqualFold applies the EqualFold predicate on the "last_upload_filename" field.
func LastUploadFilenameEqualFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEqualFold(FieldLastUploadFilename, v))
}

// LastUploadFilenameContainsFold applies the ContainsFold predicate on the "last_upload_filename" field.
func LastUploadFilenameContainsFold(v string) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldContainsFold(FieldLastUploadFilename, v))
}

// LastUploadAtEQ applies the EQ predicate on the "last_upload_at" field.
func LastUploadAtEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldLastUploadAt, v))
}

// LastUploadAtNEQ applies the NEQ predicate on the "last_upload_at" field.
func LastUploadAtNEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldLastUploadAt, v))
}

// LastUploadAtIn applies the In predicate on the "last_upload_at" field.
func LastUploadAtIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldLastUploadAt, vs...))
}

// LastUploadAtNotIn applies the NotIn predicate on the "last_upload_at" field.
func LastUploadAtNotIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldLastUploadAt, vs...))
}

// LastUploadAtGT applies the GT predicate on the "last_upload_at" field.
func LastUploadAtGT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldLastUploadAt, v))
}

// LastUploadAtGTE applies the GTE predicate on the "last_upload_at" field.
func LastUploadAtGTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldLastUploadAt, v))
}

// LastUploadAtLT applies the LT predicate on the "last_upload_at" field.
func LastUploadAtLT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldLastUploadAt, v))
}

// LastUploadAtLTE applies the LTE predicate on the "last_upload_at" field.
func LastUploadAtLTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldLastUploadAt, v))
}

// LastUploadAtIsNil applies the IsNil predicate on the "last_upload_at" field.
func LastUploadAtIsNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIsNull(FieldLastUploadAt))
}

// LastUploadAtNotNil applies the NotNil predicate on the "last_upload_at" field.
func LastUploadAtNotNil() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotNull(FieldLastUploadAt))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldIsDeleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSkills applies the HasEdge predicate on the "skills" edge.
func HasSkills() predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SkillsTable, SkillsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillsWith applies the HasEdge predicate on the "skills" edge with a given conditions (other predicates).
func HasSkillsWith(preds ...predicate.AgentSkill) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(func(s *sql.Selector) {
		step := newSkillsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSkillRepo) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSkillRepo) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSkillRepo) predicate.AgentSkillRepo {
	return predicate.AgentSkillRepo(sql.NotPredicates(p))
}
