// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/mcptool"
	"github.com/chaitin/MonkeyCode/backend/db/mcpupstream"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/chaitin/MonkeyCode/backend/db/team"
	"github.com/chaitin/MonkeyCode/backend/db/teamgroup"
	"github.com/chaitin/MonkeyCode/backend/db/teamgroupmcpupstream"
	"github.com/chaitin/MonkeyCode/backend/db/user"
	"github.com/google/uuid"
)

// MCPUpstreamQuery is the builder for querying MCPUpstream entities.
type MCPUpstreamQuery struct {
	config
	ctx                       *QueryContext
	order                     []mcpupstream.OrderOption
	inters                    []Interceptor
	predicates                []predicate.MCPUpstream
	withTools                 *MCPToolQuery
	withUser                  *UserQuery
	withTeam                  *TeamQuery
	withGroups                *TeamGroupQuery
	withTeamGroupMcpUpstreams *TeamGroupMCPUpstreamQuery
	modifiers                 []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MCPUpstreamQuery builder.
func (_q *MCPUpstreamQuery) Where(ps ...predicate.MCPUpstream) *MCPUpstreamQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MCPUpstreamQuery) Limit(limit int) *MCPUpstreamQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MCPUpstreamQuery) Offset(offset int) *MCPUpstreamQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MCPUpstreamQuery) Unique(unique bool) *MCPUpstreamQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MCPUpstreamQuery) Order(o ...mcpupstream.OrderOption) *MCPUpstreamQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTools chains the current query on the "tools" edge.
func (_q *MCPUpstreamQuery) QueryTools() *MCPToolQuery {
	query := (&MCPToolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpupstream.Table, mcpupstream.FieldID, selector),
			sqlgraph.To(mcptool.Table, mcptool.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mcpupstream.ToolsTable, mcpupstream.ToolsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *MCPUpstreamQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpupstream.Table, mcpupstream.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mcpupstream.UserTable, mcpupstream.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeam chains the current query on the "team" edge.
func (_q *MCPUpstreamQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpupstream.Table, mcpupstream.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mcpupstream.TeamTable, mcpupstream.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *MCPUpstreamQuery) QueryGroups() *TeamGroupQuery {
	query := (&TeamGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpupstream.Table, mcpupstream.FieldID, selector),
			sqlgraph.To(teamgroup.Table, teamgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, mcpupstream.GroupsTable, mcpupstream.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeamGroupMcpUpstreams chains the current query on the "team_group_mcp_upstreams" edge.
func (_q *MCPUpstreamQuery) QueryTeamGroupMcpUpstreams() *TeamGroupMCPUpstreamQuery {
	query := (&TeamGroupMCPUpstreamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpupstream.Table, mcpupstream.FieldID, selector),
			sqlgraph.To(teamgroupmcpupstream.Table, teamgroupmcpupstream.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, mcpupstream.TeamGroupMcpUpstreamsTable, mcpupstream.TeamGroupMcpUpstreamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MCPUpstream entity from the query.
// Returns a *NotFoundError when no MCPUpstream was found.
func (_q *MCPUpstreamQuery) First(ctx context.Context) (*MCPUpstream, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mcpupstream.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MCPUpstreamQuery) FirstX(ctx context.Context) *MCPUpstream {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MCPUpstream ID from the query.
// Returns a *NotFoundError when no MCPUpstream ID was found.
func (_q *MCPUpstreamQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mcpupstream.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MCPUpstreamQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MCPUpstream entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MCPUpstream entity is found.
// Returns a *NotFoundError when no MCPUpstream entities are found.
func (_q *MCPUpstreamQuery) Only(ctx context.Context) (*MCPUpstream, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mcpupstream.Label}
	default:
		return nil, &NotSingularError{mcpupstream.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MCPUpstreamQuery) OnlyX(ctx context.Context) *MCPUpstream {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MCPUpstream ID in the query.
// Returns a *NotSingularError when more than one MCPUpstream ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MCPUpstreamQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mcpupstream.Label}
	default:
		err = &NotSingularError{mcpupstream.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MCPUpstreamQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MCPUpstreams.
func (_q *MCPUpstreamQuery) All(ctx context.Context) ([]*MCPUpstream, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MCPUpstream, *MCPUpstreamQuery]()
	return withInterceptors[[]*MCPUpstream](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MCPUpstreamQuery) AllX(ctx context.Context) []*MCPUpstream {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MCPUpstream IDs.
func (_q *MCPUpstreamQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(mcpupstream.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MCPUpstreamQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MCPUpstreamQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MCPUpstreamQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MCPUpstreamQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MCPUpstreamQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MCPUpstreamQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MCPUpstreamQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MCPUpstreamQuery) Clone() *MCPUpstreamQuery {
	if _q == nil {
		return nil
	}
	return &MCPUpstreamQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]mcpupstream.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.MCPUpstream{}, _q.predicates...),
		withTools:                 _q.withTools.Clone(),
		withUser:                  _q.withUser.Clone(),
		withTeam:                  _q.withTeam.Clone(),
		withGroups:                _q.withGroups.Clone(),
		withTeamGroupMcpUpstreams: _q.withTeamGroupMcpUpstreams.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTools tells the query-builder to eager-load the nodes that are connected to
// the "tools" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MCPUpstreamQuery) WithTools(opts ...func(*MCPToolQuery)) *MCPUpstreamQuery {
	query := (&MCPToolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTools = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MCPUpstreamQuery) WithUser(opts ...func(*UserQuery)) *MCPUpstreamQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MCPUpstreamQuery) WithTeam(opts ...func(*TeamQuery)) *MCPUpstreamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MCPUpstreamQuery) WithGroups(opts ...func(*TeamGroupQuery)) *MCPUpstreamQuery {
	query := (&TeamGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// WithTeamGroupMcpUpstreams tells the query-builder to eager-load the nodes that are connected to
// the "team_group_mcp_upstreams" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MCPUpstreamQuery) WithTeamGroupMcpUpstreams(opts ...func(*TeamGroupMCPUpstreamQuery)) *MCPUpstreamQuery {
	query := (&TeamGroupMCPUpstreamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeamGroupMcpUpstreams = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MCPUpstream.Query().
//		GroupBy(mcpupstream.FieldDeletedAt).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *MCPUpstreamQuery) GroupBy(field string, fields ...string) *MCPUpstreamGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MCPUpstreamGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = mcpupstream.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//	}
//
//	client.MCPUpstream.Query().
//		Select(mcpupstream.FieldDeletedAt).
//		Scan(ctx, &v)
func (_q *MCPUpstreamQuery) Select(fields ...string) *MCPUpstreamSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MCPUpstreamSelect{MCPUpstreamQuery: _q}
	sbuild.label = mcpupstream.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MCPUpstreamSelect configured with the given aggregations.
func (_q *MCPUpstreamQuery) Aggregate(fns ...AggregateFunc) *MCPUpstreamSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MCPUpstreamQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !mcpupstream.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MCPUpstreamQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MCPUpstream, error) {
	var (
		nodes       = []*MCPUpstream{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTools != nil,
			_q.withUser != nil,
			_q.withTeam != nil,
			_q.withGroups != nil,
			_q.withTeamGroupMcpUpstreams != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MCPUpstream).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MCPUpstream{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTools; query != nil {
		if err := _q.loadTools(ctx, query, nodes,
			func(n *MCPUpstream) { n.Edges.Tools = []*MCPTool{} },
			func(n *MCPUpstream, e *MCPTool) { n.Edges.Tools = append(n.Edges.Tools, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *MCPUpstream, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *MCPUpstream, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *MCPUpstream) { n.Edges.Groups = []*TeamGroup{} },
			func(n *MCPUpstream, e *TeamGroup) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeamGroupMcpUpstreams; query != nil {
		if err := _q.loadTeamGroupMcpUpstreams(ctx, query, nodes,
			func(n *MCPUpstream) { n.Edges.TeamGroupMcpUpstreams = []*TeamGroupMCPUpstream{} },
			func(n *MCPUpstream, e *TeamGroupMCPUpstream) {
				n.Edges.TeamGroupMcpUpstreams = append(n.Edges.TeamGroupMcpUpstreams, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MCPUpstreamQuery) loadTools(ctx context.Context, query *MCPToolQuery, nodes []*MCPUpstream, init func(*MCPUpstream), assign func(*MCPUpstream, *MCPTool)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MCPUpstream)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(mcptool.FieldUpstreamID)
	}
	query.Where(predicate.MCPTool(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(mcpupstream.ToolsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MCPUpstreamQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MCPUpstream, init func(*MCPUpstream), assign func(*MCPUpstream, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MCPUpstream)
	for i := range nodes {
		if nodes[i].UserID == nil {
			continue
		}
		fk := *nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MCPUpstreamQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*MCPUpstream, init func(*MCPUpstream), assign func(*MCPUpstream, *Team)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MCPUpstream)
	for i := range nodes {
		if nodes[i].TeamID == nil {
			continue
		}
		fk := *nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MCPUpstreamQuery) loadGroups(ctx context.Context, query *TeamGroupQuery, nodes []*MCPUpstream, init func(*MCPUpstream), assign func(*MCPUpstream, *TeamGroup)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*MCPUpstream)
	nids := make(map[uuid.UUID]map[*MCPUpstream]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(mcpupstream.GroupsTable)
		s.Join(joinT).On(s.C(teamgroup.FieldID), joinT.C(mcpupstream.GroupsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(mcpupstream.GroupsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(mcpupstream.GroupsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*MCPUpstream]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*TeamGroup](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *MCPUpstreamQuery) loadTeamGroupMcpUpstreams(ctx context.Context, query *TeamGroupMCPUpstreamQuery, nodes []*MCPUpstream, init func(*MCPUpstream), assign func(*MCPUpstream, *TeamGroupMCPUpstream)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MCPUpstream)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(teamgroupmcpupstream.FieldUpstreamID)
	}
	query.Where(predicate.TeamGroupMCPUpstream(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(mcpupstream.TeamGroupMcpUpstreamsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MCPUpstreamQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MCPUpstreamQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mcpupstream.Table, mcpupstream.Columns, sqlgraph.NewFieldSpec(mcpupstream.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpupstream.FieldID)
		for i := range fields {
			if fields[i] != mcpupstream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(mcpupstream.FieldUserID)
		}
		if _q.withTeam != nil {
			_spec.Node.AddColumnOnce(mcpupstream.FieldTeamID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MCPUpstreamQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(mcpupstream.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = mcpupstream.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *MCPUpstreamQuery) ForUpdate(opts ...sql.LockOption) *MCPUpstreamQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *MCPUpstreamQuery) ForShare(opts ...sql.LockOption) *MCPUpstreamQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *MCPUpstreamQuery) Modify(modifiers ...func(s *sql.Selector)) *MCPUpstreamSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// MCPUpstreamGroupBy is the group-by builder for MCPUpstream entities.
type MCPUpstreamGroupBy struct {
	selector
	build *MCPUpstreamQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MCPUpstreamGroupBy) Aggregate(fns ...AggregateFunc) *MCPUpstreamGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MCPUpstreamGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MCPUpstreamQuery, *MCPUpstreamGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MCPUpstreamGroupBy) sqlScan(ctx context.Context, root *MCPUpstreamQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MCPUpstreamSelect is the builder for selecting fields of MCPUpstream entities.
type MCPUpstreamSelect struct {
	*MCPUpstreamQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MCPUpstreamSelect) Aggregate(fns ...AggregateFunc) *MCPUpstreamSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MCPUpstreamSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MCPUpstreamQuery, *MCPUpstreamSelect](ctx, _s.MCPUpstreamQuery, _s, _s.inters, v)
}

func (_s *MCPUpstreamSelect) sqlScan(ctx context.Context, root *MCPUpstreamQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *MCPUpstreamSelect) Modify(modifiers ...func(s *sql.Selector)) *MCPUpstreamSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
