// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/consts"
	"github.com/chaitin/MonkeyCode/backend/db/notifychannel"
	"github.com/chaitin/MonkeyCode/backend/db/notifysubscription"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// NotifySubscriptionUpdate is the builder for updating NotifySubscription entities.
type NotifySubscriptionUpdate struct {
	config
	hooks     []Hook
	mutation  *NotifySubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotifySubscriptionUpdate builder.
func (_u *NotifySubscriptionUpdate) Where(ps ...predicate.NotifySubscription) *NotifySubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotifySubscriptionUpdate) SetDeletedAt(v time.Time) *NotifySubscriptionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableDeletedAt(v *time.Time) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotifySubscriptionUpdate) ClearDeletedAt() *NotifySubscriptionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *NotifySubscriptionUpdate) SetChannelID(v uuid.UUID) *NotifySubscriptionUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableChannelID(v *uuid.UUID) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotifySubscriptionUpdate) SetScope(v string) *NotifySubscriptionUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableScope(v *string) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *NotifySubscriptionUpdate) SetEventTypes(v []consts.NotifyEventType) *NotifySubscriptionUpdate {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *NotifySubscriptionUpdate) AppendEventTypes(v []consts.NotifyEventType) *NotifySubscriptionUpdate {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifySubscriptionUpdate) SetEnabled(v bool) *NotifySubscriptionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableEnabled(v *bool) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotifySubscriptionUpdate) SetCreatedAt(v time.Time) *NotifySubscriptionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableCreatedAt(v *time.Time) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifySubscriptionUpdate) SetUpdatedAt(v time.Time) *NotifySubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the NotifyChannel entity.
func (_u *NotifySubscriptionUpdate) SetChannel(v *NotifyChannel) *NotifySubscriptionUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the NotifySubscriptionMutation object of the builder.
func (_u *NotifySubscriptionUpdate) Mutation() *NotifySubscriptionMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the NotifyChannel entity.
func (_u *NotifySubscriptionUpdate) ClearChannel() *NotifySubscriptionUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifySubscriptionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifySubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifySubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifySubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifySubscriptionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if notifysubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized notifysubscription.UpdateDefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := notifysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifySubscriptionUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "NotifySubscription.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotifySubscriptionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotifySubscriptionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotifySubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifysubscription.Table, notifysubscription.Columns, sqlgraph.NewFieldSpec(notifysubscription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notifysubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notifysubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notifysubscription.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(notifysubscription.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifysubscription.FieldEventTypes, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notifysubscription.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.ChannelTable,
			Columns: []string{notifysubscription.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.ChannelTable,
			Columns: []string{notifysubscription.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifySubscriptionUpdateOne is the builder for updating a single NotifySubscription entity.
type NotifySubscriptionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotifySubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotifySubscriptionUpdateOne) SetDeletedAt(v time.Time) *NotifySubscriptionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableDeletedAt(v *time.Time) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotifySubscriptionUpdateOne) ClearDeletedAt() *NotifySubscriptionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *NotifySubscriptionUpdateOne) SetChannelID(v uuid.UUID) *NotifySubscriptionUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableChannelID(v *uuid.UUID) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotifySubscriptionUpdateOne) SetScope(v string) *NotifySubscriptionUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableScope(v *string) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *NotifySubscriptionUpdateOne) SetEventTypes(v []consts.NotifyEventType) *NotifySubscriptionUpdateOne {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *NotifySubscriptionUpdateOne) AppendEventTypes(v []consts.NotifyEventType) *NotifySubscriptionUpdateOne {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifySubscriptionUpdateOne) SetEnabled(v bool) *NotifySubscriptionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableEnabled(v *bool) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotifySubscriptionUpdateOne) SetCreatedAt(v time.Time) *NotifySubscriptionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableCreatedAt(v *time.Time) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifySubscriptionUpdateOne) SetUpdatedAt(v time.Time) *NotifySubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannel sets the "channel" edge to the NotifyChannel entity.
func (_u *NotifySubscriptionUpdateOne) SetChannel(v *NotifyChannel) *NotifySubscriptionUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the NotifySubscriptionMutation object of the builder.
func (_u *NotifySubscriptionUpdateOne) Mutation() *NotifySubscriptionMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the NotifyChannel entity.
func (_u *NotifySubscriptionUpdateOne) ClearChannel() *NotifySubscriptionUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the NotifySubscriptionUpdate builder.
func (_u *NotifySubscriptionUpdateOne) Where(ps ...predicate.NotifySubscription) *NotifySubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifySubscriptionUpdateOne) Select(field string, fields ...string) *NotifySubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifySubscription entity.
func (_u *NotifySubscriptionUpdateOne) Save(ctx context.Context) (*NotifySubscription, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifySubscriptionUpdateOne) SaveX(ctx context.Context) *NotifySubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifySubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifySubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifySubscriptionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if notifysubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized notifysubscription.UpdateDefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := notifysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifySubscriptionUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "NotifySubscription.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotifySubscriptionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotifySubscriptionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotifySubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *NotifySubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifysubscription.Table, notifysubscription.Columns, sqlgraph.NewFieldSpec(notifysubscription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "NotifySubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifysubscription.FieldID)
		for _, f := range fields {
			if !notifysubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != notifysubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notifysubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notifysubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notifysubscription.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(notifysubscription.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifysubscription.FieldEventTypes, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notifysubscription.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.ChannelTable,
			Columns: []string{notifysubscription.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.ChannelTable,
			Columns: []string{notifysubscription.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotifySubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
