// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/gitidentity"
	"github.com/chaitin/MonkeyCode/backend/db/image"
	"github.com/chaitin/MonkeyCode/backend/db/model"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/chaitin/MonkeyCode/backend/db/project"
	"github.com/chaitin/MonkeyCode/backend/db/projectissue"
	"github.com/chaitin/MonkeyCode/backend/db/projecttask"
	"github.com/chaitin/MonkeyCode/backend/db/task"
	"github.com/google/uuid"
)

// ProjectTaskQuery is the builder for querying ProjectTask entities.
type ProjectTaskQuery struct {
	config
	ctx             *QueryContext
	order           []projecttask.OrderOption
	inters          []Interceptor
	predicates      []predicate.ProjectTask
	withTask        *TaskQuery
	withModel       *ModelQuery
	withImage       *ImageQuery
	withGitIdentity *GitIdentityQuery
	withProject     *ProjectQuery
	withIssue       *ProjectIssueQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectTaskQuery builder.
func (_q *ProjectTaskQuery) Where(ps ...predicate.ProjectTask) *ProjectTaskQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProjectTaskQuery) Limit(limit int) *ProjectTaskQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProjectTaskQuery) Offset(offset int) *ProjectTaskQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProjectTaskQuery) Unique(unique bool) *ProjectTaskQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProjectTaskQuery) Order(o ...projecttask.OrderOption) *ProjectTaskQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTask chains the current query on the "task" edge.
func (_q *ProjectTaskQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.TaskTable, projecttask.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModel chains the current query on the "model" edge.
func (_q *ProjectTaskQuery) QueryModel() *ModelQuery {
	query := (&ModelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(model.Table, model.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.ModelTable, projecttask.ModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryImage chains the current query on the "image" edge.
func (_q *ProjectTaskQuery) QueryImage() *ImageQuery {
	query := (&ImageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.ImageTable, projecttask.ImageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGitIdentity chains the current query on the "git_identity" edge.
func (_q *ProjectTaskQuery) QueryGitIdentity() *GitIdentityQuery {
	query := (&GitIdentityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(gitidentity.Table, gitidentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.GitIdentityTable, projecttask.GitIdentityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *ProjectTaskQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.ProjectTable, projecttask.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIssue chains the current query on the "issue" edge.
func (_q *ProjectTaskQuery) QueryIssue() *ProjectIssueQuery {
	query := (&ProjectIssueClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttask.Table, projecttask.FieldID, selector),
			sqlgraph.To(projectissue.Table, projectissue.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projecttask.IssueTable, projecttask.IssueColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectTask entity from the query.
// Returns a *NotFoundError when no ProjectTask was found.
func (_q *ProjectTaskQuery) First(ctx context.Context) (*ProjectTask, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projecttask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProjectTaskQuery) FirstX(ctx context.Context) *ProjectTask {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectTask ID from the query.
// Returns a *NotFoundError when no ProjectTask ID was found.
func (_q *ProjectTaskQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projecttask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProjectTaskQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectTask entity is found.
// Returns a *NotFoundError when no ProjectTask entities are found.
func (_q *ProjectTaskQuery) Only(ctx context.Context) (*ProjectTask, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projecttask.Label}
	default:
		return nil, &NotSingularError{projecttask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProjectTaskQuery) OnlyX(ctx context.Context) *ProjectTask {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectTask ID in the query.
// Returns a *NotSingularError when more than one ProjectTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProjectTaskQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projecttask.Label}
	default:
		err = &NotSingularError{projecttask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProjectTaskQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectTasks.
func (_q *ProjectTaskQuery) All(ctx context.Context) ([]*ProjectTask, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectTask, *ProjectTaskQuery]()
	return withInterceptors[[]*ProjectTask](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProjectTaskQuery) AllX(ctx context.Context) []*ProjectTask {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectTask IDs.
func (_q *ProjectTaskQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(projecttask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProjectTaskQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProjectTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProjectTaskQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProjectTaskQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProjectTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProjectTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProjectTaskQuery) Clone() *ProjectTaskQuery {
	if _q == nil {
		return nil
	}
	return &ProjectTaskQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]projecttask.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.ProjectTask{}, _q.predicates...),
		withTask:        _q.withTask.Clone(),
		withModel:       _q.withModel.Clone(),
		withImage:       _q.withImage.Clone(),
		withGitIdentity: _q.withGitIdentity.Clone(),
		withProject:     _q.withProject.Clone(),
		withIssue:       _q.withIssue.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithTask(opts ...func(*TaskQuery)) *ProjectTaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTask = query
	return _q
}

// WithModel tells the query-builder to eager-load the nodes that are connected to
// the "model" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithModel(opts ...func(*ModelQuery)) *ProjectTaskQuery {
	query := (&ModelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModel = query
	return _q
}

// WithImage tells the query-builder to eager-load the nodes that are connected to
// the "image" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithImage(opts ...func(*ImageQuery)) *ProjectTaskQuery {
	query := (&ImageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withImage = query
	return _q
}

// WithGitIdentity tells the query-builder to eager-load the nodes that are connected to
// the "git_identity" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithGitIdentity(opts ...func(*GitIdentityQuery)) *ProjectTaskQuery {
	query := (&GitIdentityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGitIdentity = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithProject(opts ...func(*ProjectQuery)) *ProjectTaskQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithIssue tells the query-builder to eager-load the nodes that are connected to
// the "issue" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTaskQuery) WithIssue(opts ...func(*ProjectIssueQuery)) *ProjectTaskQuery {
	query := (&ProjectIssueClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIssue = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID uuid.UUID `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectTask.Query().
//		GroupBy(projecttask.FieldTaskID).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *ProjectTaskQuery) GroupBy(field string, fields ...string) *ProjectTaskGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectTaskGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = projecttask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID uuid.UUID `json:"task_id,omitempty"`
//	}
//
//	client.ProjectTask.Query().
//		Select(projecttask.FieldTaskID).
//		Scan(ctx, &v)
func (_q *ProjectTaskQuery) Select(fields ...string) *ProjectTaskSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProjectTaskSelect{ProjectTaskQuery: _q}
	sbuild.label = projecttask.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectTaskSelect configured with the given aggregations.
func (_q *ProjectTaskQuery) Aggregate(fns ...AggregateFunc) *ProjectTaskSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProjectTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !projecttask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProjectTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectTask, error) {
	var (
		nodes       = []*ProjectTask{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withTask != nil,
			_q.withModel != nil,
			_q.withImage != nil,
			_q.withGitIdentity != nil,
			_q.withProject != nil,
			_q.withIssue != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectTask{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTask; query != nil {
		if err := _q.loadTask(ctx, query, nodes, nil,
			func(n *ProjectTask, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withModel; query != nil {
		if err := _q.loadModel(ctx, query, nodes, nil,
			func(n *ProjectTask, e *Model) { n.Edges.Model = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withImage; query != nil {
		if err := _q.loadImage(ctx, query, nodes, nil,
			func(n *ProjectTask, e *Image) { n.Edges.Image = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGitIdentity; query != nil {
		if err := _q.loadGitIdentity(ctx, query, nodes, nil,
			func(n *ProjectTask, e *GitIdentity) { n.Edges.GitIdentity = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *ProjectTask, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIssue; query != nil {
		if err := _q.loadIssue(ctx, query, nodes, nil,
			func(n *ProjectTask, e *ProjectIssue) { n.Edges.Issue = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProjectTaskQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *Task)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTaskQuery) loadModel(ctx context.Context, query *ModelQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *Model)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		fk := nodes[i].ModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(model.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTaskQuery) loadImage(ctx context.Context, query *ImageQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *Image)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		fk := nodes[i].ImageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(image.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "image_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTaskQuery) loadGitIdentity(ctx context.Context, query *GitIdentityQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *GitIdentity)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		fk := nodes[i].GitIdentityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(gitidentity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "git_identity_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTaskQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		if nodes[i].ProjectID == nil {
			continue
		}
		fk := *nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTaskQuery) loadIssue(ctx context.Context, query *ProjectIssueQuery, nodes []*ProjectTask, init func(*ProjectTask), assign func(*ProjectTask, *ProjectIssue)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTask)
	for i := range nodes {
		fk := nodes[i].IssueID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(projectissue.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "issue_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProjectTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProjectTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projecttask.Table, projecttask.Columns, sqlgraph.NewFieldSpec(projecttask.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projecttask.FieldID)
		for i := range fields {
			if fields[i] != projecttask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTask != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldTaskID)
		}
		if _q.withModel != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldModelID)
		}
		if _q.withImage != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldImageID)
		}
		if _q.withGitIdentity != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldGitIdentityID)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldProjectID)
		}
		if _q.withIssue != nil {
			_spec.Node.AddColumnOnce(projecttask.FieldIssueID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProjectTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(projecttask.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = projecttask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ProjectTaskQuery) ForUpdate(opts ...sql.LockOption) *ProjectTaskQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ProjectTaskQuery) ForShare(opts ...sql.LockOption) *ProjectTaskQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ProjectTaskQuery) Modify(modifiers ...func(s *sql.Selector)) *ProjectTaskSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ProjectTaskGroupBy is the group-by builder for ProjectTask entities.
type ProjectTaskGroupBy struct {
	selector
	build *ProjectTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProjectTaskGroupBy) Aggregate(fns ...AggregateFunc) *ProjectTaskGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProjectTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectTaskQuery, *ProjectTaskGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProjectTaskGroupBy) sqlScan(ctx context.Context, root *ProjectTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectTaskSelect is the builder for selecting fields of ProjectTask entities.
type ProjectTaskSelect struct {
	*ProjectTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProjectTaskSelect) Aggregate(fns ...AggregateFunc) *ProjectTaskSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProjectTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectTaskQuery, *ProjectTaskSelect](ctx, _s.ProjectTaskQuery, _s, _s.inters, v)
}

func (_s *ProjectTaskSelect) sqlScan(ctx context.Context, root *ProjectTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ProjectTaskSelect) Modify(modifiers ...func(s *sql.Selector)) *ProjectTaskSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
