// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/task"
	"github.com/chaitin/MonkeyCode/backend/db/taskvirtualmachine"
	"github.com/chaitin/MonkeyCode/backend/db/virtualmachine"
	"github.com/google/uuid"
)

// TaskVirtualMachineCreate is the builder for creating a TaskVirtualMachine entity.
type TaskVirtualMachineCreate struct {
	config
	mutation *TaskVirtualMachineMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *TaskVirtualMachineCreate) SetTaskID(v uuid.UUID) *TaskVirtualMachineCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetVirtualmachineID sets the "virtualmachine_id" field.
func (_c *TaskVirtualMachineCreate) SetVirtualmachineID(v string) *TaskVirtualMachineCreate {
	_c.mutation.SetVirtualmachineID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskVirtualMachineCreate) SetCreatedAt(v time.Time) *TaskVirtualMachineCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskVirtualMachineCreate) SetNillableCreatedAt(v *time.Time) *TaskVirtualMachineCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskVirtualMachineCreate) SetID(v uuid.UUID) *TaskVirtualMachineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskVirtualMachineCreate) SetTask(v *Task) *TaskVirtualMachineCreate {
	return _c.SetTaskID(v.ID)
}

// SetVirtualmachine sets the "virtualmachine" edge to the VirtualMachine entity.
func (_c *TaskVirtualMachineCreate) SetVirtualmachine(v *VirtualMachine) *TaskVirtualMachineCreate {
	return _c.SetVirtualmachineID(v.ID)
}

// Mutation returns the TaskVirtualMachineMutation object of the builder.
func (_c *TaskVirtualMachineCreate) Mutation() *TaskVirtualMachineMutation {
	return _c.mutation
}

// Save creates the TaskVirtualMachine in the database.
func (_c *TaskVirtualMachineCreate) Save(ctx context.Context) (*TaskVirtualMachine, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskVirtualMachineCreate) SaveX(ctx context.Context) *TaskVirtualMachine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskVirtualMachineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskVirtualMachineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskVirtualMachineCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskvirtualmachine.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskVirtualMachineCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`db: missing required field "TaskVirtualMachine.task_id"`)}
	}
	if _, ok := _c.mutation.VirtualmachineID(); !ok {
		return &ValidationError{Name: "virtualmachine_id", err: errors.New(`db: missing required field "TaskVirtualMachine.virtualmachine_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "TaskVirtualMachine.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`db: missing required edge "TaskVirtualMachine.task"`)}
	}
	if len(_c.mutation.VirtualmachineIDs()) == 0 {
		return &ValidationError{Name: "virtualmachine", err: errors.New(`db: missing required edge "TaskVirtualMachine.virtualmachine"`)}
	}
	return nil
}

func (_c *TaskVirtualMachineCreate) sqlSave(ctx context.Context) (*TaskVirtualMachine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskVirtualMachineCreate) createSpec() (*TaskVirtualMachine, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskVirtualMachine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskvirtualmachine.Table, sqlgraph.NewFieldSpec(taskvirtualmachine.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskvirtualmachine.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taskvirtualmachine.TaskTable,
			Columns: []string{taskvirtualmachine.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VirtualmachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   taskvirtualmachine.VirtualmachineTable,
			Columns: []string{taskvirtualmachine.VirtualmachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualmachine.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VirtualmachineID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskVirtualMachine.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskVirtualMachineUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskVirtualMachineCreate) OnConflict(opts ...sql.ConflictOption) *TaskVirtualMachineUpsertOne {
	_c.conflict = opts
	return &TaskVirtualMachineUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskVirtualMachineCreate) OnConflictColumns(columns ...string) *TaskVirtualMachineUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskVirtualMachineUpsertOne{
		create: _c,
	}
}

type (
	// TaskVirtualMachineUpsertOne is the builder for "upsert"-ing
	//  one TaskVirtualMachine node.
	TaskVirtualMachineUpsertOne struct {
		create *TaskVirtualMachineCreate
	}

	// TaskVirtualMachineUpsert is the "OnConflict" setter.
	TaskVirtualMachineUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskID sets the "task_id" field.
func (u *TaskVirtualMachineUpsert) SetTaskID(v uuid.UUID) *TaskVirtualMachineUpsert {
	u.Set(taskvirtualmachine.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsert) UpdateTaskID() *TaskVirtualMachineUpsert {
	u.SetExcluded(taskvirtualmachine.FieldTaskID)
	return u
}

// SetVirtualmachineID sets the "virtualmachine_id" field.
func (u *TaskVirtualMachineUpsert) SetVirtualmachineID(v string) *TaskVirtualMachineUpsert {
	u.Set(taskvirtualmachine.FieldVirtualmachineID, v)
	return u
}

// UpdateVirtualmachineID sets the "virtualmachine_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsert) UpdateVirtualmachineID() *TaskVirtualMachineUpsert {
	u.SetExcluded(taskvirtualmachine.FieldVirtualmachineID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskVirtualMachineUpsert) SetCreatedAt(v time.Time) *TaskVirtualMachineUpsert {
	u.Set(taskvirtualmachine.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsert) UpdateCreatedAt() *TaskVirtualMachineUpsert {
	u.SetExcluded(taskvirtualmachine.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskvirtualmachine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskVirtualMachineUpsertOne) UpdateNewValues() *TaskVirtualMachineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskvirtualmachine.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskVirtualMachineUpsertOne) Ignore() *TaskVirtualMachineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskVirtualMachineUpsertOne) DoNothing() *TaskVirtualMachineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskVirtualMachineCreate.OnConflict
// documentation for more info.
func (u *TaskVirtualMachineUpsertOne) Update(set func(*TaskVirtualMachineUpsert)) *TaskVirtualMachineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskVirtualMachineUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskVirtualMachineUpsertOne) SetTaskID(v uuid.UUID) *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertOne) UpdateTaskID() *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateTaskID()
	})
}

// SetVirtualmachineID sets the "virtualmachine_id" field.
func (u *TaskVirtualMachineUpsertOne) SetVirtualmachineID(v string) *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetVirtualmachineID(v)
	})
}

// UpdateVirtualmachineID sets the "virtualmachine_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertOne) UpdateVirtualmachineID() *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateVirtualmachineID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskVirtualMachineUpsertOne) SetCreatedAt(v time.Time) *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertOne) UpdateCreatedAt() *TaskVirtualMachineUpsertOne {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TaskVirtualMachineUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TaskVirtualMachineCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskVirtualMachineUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskVirtualMachineUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: TaskVirtualMachineUpsertOne.ID is not supported by MySQL driver. Use TaskVirtualMachineUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskVirtualMachineUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskVirtualMachineCreateBulk is the builder for creating many TaskVirtualMachine entities in bulk.
type TaskVirtualMachineCreateBulk struct {
	config
	err      error
	builders []*TaskVirtualMachineCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskVirtualMachine entities in the database.
func (_c *TaskVirtualMachineCreateBulk) Save(ctx context.Context) ([]*TaskVirtualMachine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskVirtualMachine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskVirtualMachineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskVirtualMachineCreateBulk) SaveX(ctx context.Context) []*TaskVirtualMachine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskVirtualMachineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskVirtualMachineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskVirtualMachine.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskVirtualMachineUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskVirtualMachineCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskVirtualMachineUpsertBulk {
	_c.conflict = opts
	return &TaskVirtualMachineUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskVirtualMachineCreateBulk) OnConflictColumns(columns ...string) *TaskVirtualMachineUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskVirtualMachineUpsertBulk{
		create: _c,
	}
}

// TaskVirtualMachineUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskVirtualMachine nodes.
type TaskVirtualMachineUpsertBulk struct {
	create *TaskVirtualMachineCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskvirtualmachine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskVirtualMachineUpsertBulk) UpdateNewValues() *TaskVirtualMachineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskvirtualmachine.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskVirtualMachine.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskVirtualMachineUpsertBulk) Ignore() *TaskVirtualMachineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskVirtualMachineUpsertBulk) DoNothing() *TaskVirtualMachineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskVirtualMachineCreateBulk.OnConflict
// documentation for more info.
func (u *TaskVirtualMachineUpsertBulk) Update(set func(*TaskVirtualMachineUpsert)) *TaskVirtualMachineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskVirtualMachineUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskVirtualMachineUpsertBulk) SetTaskID(v uuid.UUID) *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertBulk) UpdateTaskID() *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateTaskID()
	})
}

// SetVirtualmachineID sets the "virtualmachine_id" field.
func (u *TaskVirtualMachineUpsertBulk) SetVirtualmachineID(v string) *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetVirtualmachineID(v)
	})
}

// UpdateVirtualmachineID sets the "virtualmachine_id" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertBulk) UpdateVirtualmachineID() *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateVirtualmachineID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskVirtualMachineUpsertBulk) SetCreatedAt(v time.Time) *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskVirtualMachineUpsertBulk) UpdateCreatedAt() *TaskVirtualMachineUpsertBulk {
	return u.Update(func(s *TaskVirtualMachineUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TaskVirtualMachineUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the TaskVirtualMachineCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TaskVirtualMachineCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskVirtualMachineUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
