// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/chaitin/MonkeyCode/backend/db/teamoidcconfig"
)

// TeamOIDCConfigDelete is the builder for deleting a TeamOIDCConfig entity.
type TeamOIDCConfigDelete struct {
	config
	hooks    []Hook
	mutation *TeamOIDCConfigMutation
}

// Where appends a list predicates to the TeamOIDCConfigDelete builder.
func (_d *TeamOIDCConfigDelete) Where(ps ...predicate.TeamOIDCConfig) *TeamOIDCConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamOIDCConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamOIDCConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamOIDCConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamoidcconfig.Table, sqlgraph.NewFieldSpec(teamoidcconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamOIDCConfigDeleteOne is the builder for deleting a single TeamOIDCConfig entity.
type TeamOIDCConfigDeleteOne struct {
	_d *TeamOIDCConfigDelete
}

// Where appends a list predicates to the TeamOIDCConfigDelete builder.
func (_d *TeamOIDCConfigDeleteOne) Where(ps ...predicate.TeamOIDCConfig) *TeamOIDCConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamOIDCConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamoidcconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamOIDCConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
