// Code generated by ent, DO NOT EDIT.

package virtualmachinerecyclerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the virtualmachinerecyclerecord type in the database.
	Label = "virtual_machine_recycle_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVirtualmachineID holds the string denoting the virtualmachine_id field in the database.
	FieldVirtualmachineID = "virtualmachine_id"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldHostID holds the string denoting the host_id field in the database.
	FieldHostID = "host_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTaskIds holds the string denoting the task_ids field in the database.
	FieldTaskIds = "task_ids"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldRemoteDeleted holds the string denoting the remote_deleted field in the database.
	FieldRemoteDeleted = "remote_deleted"
	// FieldRecycledAt holds the string denoting the recycled_at field in the database.
	FieldRecycledAt = "recycled_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the virtualmachinerecyclerecord in the database.
	Table = "virtualmachine_recycle_records"
)

// Columns holds all SQL columns for virtualmachinerecyclerecord fields.
var Columns = []string{
	FieldID,
	FieldVirtualmachineID,
	FieldEnvironmentID,
	FieldHostID,
	FieldUserID,
	FieldTaskIds,
	FieldMethod,
	FieldRemoteDeleted,
	FieldRecycledAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRemoteDeleted holds the default value on creation for the "remote_deleted" field.
	DefaultRemoteDeleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the VirtualMachineRecycleRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVirtualmachineID orders the results by the virtualmachine_id field.
func ByVirtualmachineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVirtualmachineID, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByHostID orders the results by the host_id field.
func ByHostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByRemoteDeleted orders the results by the remote_deleted field.
func ByRemoteDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteDeleted, opts...).ToFunc()
}

// ByRecycledAt orders the results by the recycled_at field.
func ByRecycledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecycledAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
