// Code generated by ent, DO NOT EDIT.

package gittask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldTaskID, v))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldRepoID, v))
}

// SubjectType applies equality check predicate on the "subject_type" field. It's identical to SubjectTypeEQ.
func SubjectType(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectNumber applies equality check predicate on the "subject_number" field. It's identical to SubjectNumberEQ.
func SubjectNumber(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectNumber, v))
}

// SubjectURL applies equality check predicate on the "subject_url" field. It's identical to SubjectURLEQ.
func SubjectURL(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectURL, v))
}

// SubjectTitle applies equality check predicate on the "subject_title" field. It's identical to SubjectTitleEQ.
func SubjectTitle(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectTitle, v))
}

// PromptID applies equality check predicate on the "prompt_id" field. It's identical to PromptIDEQ.
func PromptID(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldPromptID, v))
}

// ShowURL applies equality check predicate on the "show_url" field. It's identical to ShowURLEQ.
func ShowURL(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldShowURL, v))
}

// GithubInstallationID applies equality check predicate on the "github_installation_id" field. It's identical to GithubInstallationIDEQ.
func GithubInstallationID(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldGithubInstallationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldTaskID, vs...))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v uuid.UUID) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldRepoID, v))
}

// RepoIDIsNil applies the IsNil predicate on the "repo_id" field.
func RepoIDIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldRepoID))
}

// RepoIDNotNil applies the NotNil predicate on the "repo_id" field.
func RepoIDNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldRepoID))
}

// SubjectTypeEQ applies the EQ predicate on the "subject_type" field.
func SubjectTypeEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectTypeNEQ applies the NEQ predicate on the "subject_type" field.
func SubjectTypeNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldSubjectType, v))
}

// SubjectTypeIn applies the In predicate on the "subject_type" field.
func SubjectTypeIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldSubjectType, vs...))
}

// SubjectTypeNotIn applies the NotIn predicate on the "subject_type" field.
func SubjectTypeNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldSubjectType, vs...))
}

// SubjectTypeGT applies the GT predicate on the "subject_type" field.
func SubjectTypeGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldSubjectType, v))
}

// SubjectTypeGTE applies the GTE predicate on the "subject_type" field.
func SubjectTypeGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldSubjectType, v))
}

// SubjectTypeLT applies the LT predicate on the "subject_type" field.
func SubjectTypeLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldSubjectType, v))
}

// SubjectTypeLTE applies the LTE predicate on the "subject_type" field.
func SubjectTypeLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldSubjectType, v))
}

// SubjectTypeContains applies the Contains predicate on the "subject_type" field.
func SubjectTypeContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldSubjectType, v))
}

// SubjectTypeHasPrefix applies the HasPrefix predicate on the "subject_type" field.
func SubjectTypeHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldSubjectType, v))
}

// SubjectTypeHasSuffix applies the HasSuffix predicate on the "subject_type" field.
func SubjectTypeHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldSubjectType, v))
}

// SubjectTypeEqualFold applies the EqualFold predicate on the "subject_type" field.
func SubjectTypeEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldSubjectType, v))
}

// SubjectTypeContainsFold applies the ContainsFold predicate on the "subject_type" field.
func SubjectTypeContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldSubjectType, v))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldSubjectID, v))
}

// SubjectIDContains applies the Contains predicate on the "subject_id" field.
func SubjectIDContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldSubjectID, v))
}

// SubjectIDHasPrefix applies the HasPrefix predicate on the "subject_id" field.
func SubjectIDHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldSubjectID, v))
}

// SubjectIDHasSuffix applies the HasSuffix predicate on the "subject_id" field.
func SubjectIDHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldSubjectID, v))
}

// SubjectIDIsNil applies the IsNil predicate on the "subject_id" field.
func SubjectIDIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldSubjectID))
}

// SubjectIDNotNil applies the NotNil predicate on the "subject_id" field.
func SubjectIDNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldSubjectID))
}

// SubjectIDEqualFold applies the EqualFold predicate on the "subject_id" field.
func SubjectIDEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldSubjectID, v))
}

// SubjectIDContainsFold applies the ContainsFold predicate on the "subject_id" field.
func SubjectIDContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldSubjectID, v))
}

// SubjectNumberEQ applies the EQ predicate on the "subject_number" field.
func SubjectNumberEQ(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectNumber, v))
}

// SubjectNumberNEQ applies the NEQ predicate on the "subject_number" field.
func SubjectNumberNEQ(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldSubjectNumber, v))
}

// SubjectNumberIn applies the In predicate on the "subject_number" field.
func SubjectNumberIn(vs ...int) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldSubjectNumber, vs...))
}

// SubjectNumberNotIn applies the NotIn predicate on the "subject_number" field.
func SubjectNumberNotIn(vs ...int) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldSubjectNumber, vs...))
}

// SubjectNumberGT applies the GT predicate on the "subject_number" field.
func SubjectNumberGT(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldSubjectNumber, v))
}

// SubjectNumberGTE applies the GTE predicate on the "subject_number" field.
func SubjectNumberGTE(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldSubjectNumber, v))
}

// SubjectNumberLT applies the LT predicate on the "subject_number" field.
func SubjectNumberLT(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldSubjectNumber, v))
}

// SubjectNumberLTE applies the LTE predicate on the "subject_number" field.
func SubjectNumberLTE(v int) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldSubjectNumber, v))
}

// SubjectNumberIsNil applies the IsNil predicate on the "subject_number" field.
func SubjectNumberIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldSubjectNumber))
}

// SubjectNumberNotNil applies the NotNil predicate on the "subject_number" field.
func SubjectNumberNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldSubjectNumber))
}

// SubjectURLEQ applies the EQ predicate on the "subject_url" field.
func SubjectURLEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectURL, v))
}

// SubjectURLNEQ applies the NEQ predicate on the "subject_url" field.
func SubjectURLNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldSubjectURL, v))
}

// SubjectURLIn applies the In predicate on the "subject_url" field.
func SubjectURLIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldSubjectURL, vs...))
}

// SubjectURLNotIn applies the NotIn predicate on the "subject_url" field.
func SubjectURLNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldSubjectURL, vs...))
}

// SubjectURLGT applies the GT predicate on the "subject_url" field.
func SubjectURLGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldSubjectURL, v))
}

// SubjectURLGTE applies the GTE predicate on the "subject_url" field.
func SubjectURLGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldSubjectURL, v))
}

// SubjectURLLT applies the LT predicate on the "subject_url" field.
func SubjectURLLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldSubjectURL, v))
}

// SubjectURLLTE applies the LTE predicate on the "subject_url" field.
func SubjectURLLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldSubjectURL, v))
}

// SubjectURLContains applies the Contains predicate on the "subject_url" field.
func SubjectURLContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldSubjectURL, v))
}

// SubjectURLHasPrefix applies the HasPrefix predicate on the "subject_url" field.
func SubjectURLHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldSubjectURL, v))
}

// SubjectURLHasSuffix applies the HasSuffix predicate on the "subject_url" field.
func SubjectURLHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldSubjectURL, v))
}

// SubjectURLIsNil applies the IsNil predicate on the "subject_url" field.
func SubjectURLIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldSubjectURL))
}

// SubjectURLNotNil applies the NotNil predicate on the "subject_url" field.
func SubjectURLNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldSubjectURL))
}

// SubjectURLEqualFold applies the EqualFold predicate on the "subject_url" field.
func SubjectURLEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldSubjectURL, v))
}

// SubjectURLContainsFold applies the ContainsFold predicate on the "subject_url" field.
func SubjectURLContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldSubjectURL, v))
}

// SubjectTitleEQ applies the EQ predicate on the "subject_title" field.
func SubjectTitleEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldSubjectTitle, v))
}

// SubjectTitleNEQ applies the NEQ predicate on the "subject_title" field.
func SubjectTitleNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldSubjectTitle, v))
}

// SubjectTitleIn applies the In predicate on the "subject_title" field.
func SubjectTitleIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldSubjectTitle, vs...))
}

// SubjectTitleNotIn applies the NotIn predicate on the "subject_title" field.
func SubjectTitleNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldSubjectTitle, vs...))
}

// SubjectTitleGT applies the GT predicate on the "subject_title" field.
func SubjectTitleGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldSubjectTitle, v))
}

// SubjectTitleGTE applies the GTE predicate on the "subject_title" field.
func SubjectTitleGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldSubjectTitle, v))
}

// SubjectTitleLT applies the LT predicate on the "subject_title" field.
func SubjectTitleLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldSubjectTitle, v))
}

// SubjectTitleLTE applies the LTE predicate on the "subject_title" field.
func SubjectTitleLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldSubjectTitle, v))
}

// SubjectTitleContains applies the Contains predicate on the "subject_title" field.
func SubjectTitleContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldSubjectTitle, v))
}

// SubjectTitleHasPrefix applies the HasPrefix predicate on the "subject_title" field.
func SubjectTitleHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldSubjectTitle, v))
}

// SubjectTitleHasSuffix applies the HasSuffix predicate on the "subject_title" field.
func SubjectTitleHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldSubjectTitle, v))
}

// SubjectTitleIsNil applies the IsNil predicate on the "subject_title" field.
func SubjectTitleIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldSubjectTitle))
}

// SubjectTitleNotNil applies the NotNil predicate on the "subject_title" field.
func SubjectTitleNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldSubjectTitle))
}

// SubjectTitleEqualFold applies the EqualFold predicate on the "subject_title" field.
func SubjectTitleEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldSubjectTitle, v))
}

// SubjectTitleContainsFold applies the ContainsFold predicate on the "subject_title" field.
func SubjectTitleContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldSubjectTitle, v))
}

// PromptIDEQ applies the EQ predicate on the "prompt_id" field.
func PromptIDEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldPromptID, v))
}

// PromptIDNEQ applies the NEQ predicate on the "prompt_id" field.
func PromptIDNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldPromptID, v))
}

// PromptIDIn applies the In predicate on the "prompt_id" field.
func PromptIDIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldPromptID, vs...))
}

// PromptIDNotIn applies the NotIn predicate on the "prompt_id" field.
func PromptIDNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldPromptID, vs...))
}

// PromptIDGT applies the GT predicate on the "prompt_id" field.
func PromptIDGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldPromptID, v))
}

// PromptIDGTE applies the GTE predicate on the "prompt_id" field.
func PromptIDGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldPromptID, v))
}

// PromptIDLT applies the LT predicate on the "prompt_id" field.
func PromptIDLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldPromptID, v))
}

// PromptIDLTE applies the LTE predicate on the "prompt_id" field.
func PromptIDLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldPromptID, v))
}

// PromptIDContains applies the Contains predicate on the "prompt_id" field.
func PromptIDContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldPromptID, v))
}

// PromptIDHasPrefix applies the HasPrefix predicate on the "prompt_id" field.
func PromptIDHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldPromptID, v))
}

// PromptIDHasSuffix applies the HasSuffix predicate on the "prompt_id" field.
func PromptIDHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldPromptID, v))
}

// PromptIDIsNil applies the IsNil predicate on the "prompt_id" field.
func PromptIDIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldPromptID))
}

// PromptIDNotNil applies the NotNil predicate on the "prompt_id" field.
func PromptIDNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldPromptID))
}

// PromptIDEqualFold applies the EqualFold predicate on the "prompt_id" field.
func PromptIDEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldPromptID, v))
}

// PromptIDContainsFold applies the ContainsFold predicate on the "prompt_id" field.
func PromptIDContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldPromptID, v))
}

// ShowURLEQ applies the EQ predicate on the "show_url" field.
func ShowURLEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldShowURL, v))
}

// ShowURLNEQ applies the NEQ predicate on the "show_url" field.
func ShowURLNEQ(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldShowURL, v))
}

// ShowURLIn applies the In predicate on the "show_url" field.
func ShowURLIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldShowURL, vs...))
}

// ShowURLNotIn applies the NotIn predicate on the "show_url" field.
func ShowURLNotIn(vs ...string) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldShowURL, vs...))
}

// ShowURLGT applies the GT predicate on the "show_url" field.
func ShowURLGT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldShowURL, v))
}

// ShowURLGTE applies the GTE predicate on the "show_url" field.
func ShowURLGTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldShowURL, v))
}

// ShowURLLT applies the LT predicate on the "show_url" field.
func ShowURLLT(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldShowURL, v))
}

// ShowURLLTE applies the LTE predicate on the "show_url" field.
func ShowURLLTE(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldShowURL, v))
}

// ShowURLContains applies the Contains predicate on the "show_url" field.
func ShowURLContains(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContains(FieldShowURL, v))
}

// ShowURLHasPrefix applies the HasPrefix predicate on the "show_url" field.
func ShowURLHasPrefix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasPrefix(FieldShowURL, v))
}

// ShowURLHasSuffix applies the HasSuffix predicate on the "show_url" field.
func ShowURLHasSuffix(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldHasSuffix(FieldShowURL, v))
}

// ShowURLIsNil applies the IsNil predicate on the "show_url" field.
func ShowURLIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldShowURL))
}

// ShowURLNotNil applies the NotNil predicate on the "show_url" field.
func ShowURLNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldShowURL))
}

// ShowURLEqualFold applies the EqualFold predicate on the "show_url" field.
func ShowURLEqualFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldEqualFold(FieldShowURL, v))
}

// ShowURLContainsFold applies the ContainsFold predicate on the "show_url" field.
func ShowURLContainsFold(v string) predicate.GitTask {
	return predicate.GitTask(sql.FieldContainsFold(FieldShowURL, v))
}

// GithubInstallationIDEQ applies the EQ predicate on the "github_installation_id" field.
func GithubInstallationIDEQ(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDNEQ applies the NEQ predicate on the "github_installation_id" field.
func GithubInstallationIDNEQ(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDIn applies the In predicate on the "github_installation_id" field.
func GithubInstallationIDIn(vs ...int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDNotIn applies the NotIn predicate on the "github_installation_id" field.
func GithubInstallationIDNotIn(vs ...int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDGT applies the GT predicate on the "github_installation_id" field.
func GithubInstallationIDGT(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldGithubInstallationID, v))
}

// GithubInstallationIDGTE applies the GTE predicate on the "github_installation_id" field.
func GithubInstallationIDGTE(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldGithubInstallationID, v))
}

// GithubInstallationIDLT applies the LT predicate on the "github_installation_id" field.
func GithubInstallationIDLT(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldGithubInstallationID, v))
}

// GithubInstallationIDLTE applies the LTE predicate on the "github_installation_id" field.
func GithubInstallationIDLTE(v int64) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldGithubInstallationID, v))
}

// GithubInstallationIDIsNil applies the IsNil predicate on the "github_installation_id" field.
func GithubInstallationIDIsNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldIsNull(FieldGithubInstallationID))
}

// GithubInstallationIDNotNil applies the NotNil predicate on the "github_installation_id" field.
func GithubInstallationIDNotNil() predicate.GitTask {
	return predicate.GitTask(sql.FieldNotNull(FieldGithubInstallationID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GitTask {
	return predicate.GitTask(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.GitTask {
	return predicate.GitTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.GitTask {
	return predicate.GitTask(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GitTask) predicate.GitTask {
	return predicate.GitTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GitTask) predicate.GitTask {
	return predicate.GitTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GitTask) predicate.GitTask {
	return predicate.GitTask(sql.NotPredicates(p))
}
