// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsBlocked holds the string denoting the is_blocked field in the database.
	FieldIsBlocked = "is_blocked"
	// FieldDefaultConfigs holds the string denoting the default_configs field in the database.
	FieldDefaultConfigs = "default_configs"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeIdentities holds the string denoting the identities edge name in mutations.
	EdgeIdentities = "identities"
	// EdgeAudits holds the string denoting the audits edge name in mutations.
	EdgeAudits = "audits"
	// EdgeTeams holds the string denoting the teams edge name in mutations.
	EdgeTeams = "teams"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeModels holds the string denoting the models edge name in mutations.
	EdgeModels = "models"
	// EdgeImages holds the string denoting the images edge name in mutations.
	EdgeImages = "images"
	// EdgeHosts holds the string denoting the hosts edge name in mutations.
	EdgeHosts = "hosts"
	// EdgeVms holds the string denoting the vms edge name in mutations.
	EdgeVms = "vms"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// EdgeTaskModelSwitches holds the string denoting the task_model_switches edge name in mutations.
	EdgeTaskModelSwitches = "task_model_switches"
	// EdgeGitIdentities holds the string denoting the git_identities edge name in mutations.
	EdgeGitIdentities = "git_identities"
	// EdgeProjects holds the string denoting the projects edge name in mutations.
	EdgeProjects = "projects"
	// EdgeProjectIssues holds the string denoting the project_issues edge name in mutations.
	EdgeProjectIssues = "project_issues"
	// EdgeAssignedIssues holds the string denoting the assigned_issues edge name in mutations.
	EdgeAssignedIssues = "assigned_issues"
	// EdgeProjectCollaborators holds the string denoting the project_collaborators edge name in mutations.
	EdgeProjectCollaborators = "project_collaborators"
	// EdgeProjectIssueComments holds the string denoting the project_issue_comments edge name in mutations.
	EdgeProjectIssueComments = "project_issue_comments"
	// EdgeGitBots holds the string denoting the git_bots edge name in mutations.
	EdgeGitBots = "git_bots"
	// EdgeMcpUpstreams holds the string denoting the mcp_upstreams edge name in mutations.
	EdgeMcpUpstreams = "mcp_upstreams"
	// EdgeTeamMembers holds the string denoting the team_members edge name in mutations.
	EdgeTeamMembers = "team_members"
	// EdgeTeamGroupMembers holds the string denoting the team_group_members edge name in mutations.
	EdgeTeamGroupMembers = "team_group_members"
	// EdgeGitBotUsers holds the string denoting the git_bot_users edge name in mutations.
	EdgeGitBotUsers = "git_bot_users"
	// Table holds the table name of the user in the database.
	Table = "users"
	// IdentitiesTable is the table that holds the identities relation/edge.
	IdentitiesTable = "user_identities"
	// IdentitiesInverseTable is the table name for the UserIdentity entity.
	// It exists in this package in order to avoid circular dependency with the "useridentity" package.
	IdentitiesInverseTable = "user_identities"
	// IdentitiesColumn is the table column denoting the identities relation/edge.
	IdentitiesColumn = "user_id"
	// AuditsTable is the table that holds the audits relation/edge.
	AuditsTable = "audits"
	// AuditsInverseTable is the table name for the Audit entity.
	// It exists in this package in order to avoid circular dependency with the "audit" package.
	AuditsInverseTable = "audits"
	// AuditsColumn is the table column denoting the audits relation/edge.
	AuditsColumn = "user_id"
	// TeamsTable is the table that holds the teams relation/edge. The primary key declared below.
	TeamsTable = "team_members"
	// TeamsInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamsInverseTable = "teams"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "team_group_members"
	// GroupsInverseTable is the table name for the TeamGroup entity.
	// It exists in this package in order to avoid circular dependency with the "teamgroup" package.
	GroupsInverseTable = "team_groups"
	// ModelsTable is the table that holds the models relation/edge.
	ModelsTable = "models"
	// ModelsInverseTable is the table name for the Model entity.
	// It exists in this package in order to avoid circular dependency with the "model" package.
	ModelsInverseTable = "models"
	// ModelsColumn is the table column denoting the models relation/edge.
	ModelsColumn = "user_id"
	// ImagesTable is the table that holds the images relation/edge.
	ImagesTable = "images"
	// ImagesInverseTable is the table name for the Image entity.
	// It exists in this package in order to avoid circular dependency with the "image" package.
	ImagesInverseTable = "images"
	// ImagesColumn is the table column denoting the images relation/edge.
	ImagesColumn = "user_id"
	// HostsTable is the table that holds the hosts relation/edge.
	HostsTable = "hosts"
	// HostsInverseTable is the table name for the Host entity.
	// It exists in this package in order to avoid circular dependency with the "host" package.
	HostsInverseTable = "hosts"
	// HostsColumn is the table column denoting the hosts relation/edge.
	HostsColumn = "user_id"
	// VmsTable is the table that holds the vms relation/edge.
	VmsTable = "virtualmachines"
	// VmsInverseTable is the table name for the VirtualMachine entity.
	// It exists in this package in order to avoid circular dependency with the "virtualmachine" package.
	VmsInverseTable = "virtualmachines"
	// VmsColumn is the table column denoting the vms relation/edge.
	VmsColumn = "user_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "user_id"
	// TaskModelSwitchesTable is the table that holds the task_model_switches relation/edge.
	TaskModelSwitchesTable = "task_model_switches"
	// TaskModelSwitchesInverseTable is the table name for the TaskModelSwitch entity.
	// It exists in this package in order to avoid circular dependency with the "taskmodelswitch" package.
	TaskModelSwitchesInverseTable = "task_model_switches"
	// TaskModelSwitchesColumn is the table column denoting the task_model_switches relation/edge.
	TaskModelSwitchesColumn = "user_id"
	// GitIdentitiesTable is the table that holds the git_identities relation/edge.
	GitIdentitiesTable = "git_identities"
	// GitIdentitiesInverseTable is the table name for the GitIdentity entity.
	// It exists in this package in order to avoid circular dependency with the "gitidentity" package.
	GitIdentitiesInverseTable = "git_identities"
	// GitIdentitiesColumn is the table column denoting the git_identities relation/edge.
	GitIdentitiesColumn = "user_id"
	// ProjectsTable is the table that holds the projects relation/edge.
	ProjectsTable = "projects"
	// ProjectsInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectsInverseTable = "projects"
	// ProjectsColumn is the table column denoting the projects relation/edge.
	ProjectsColumn = "user_id"
	// ProjectIssuesTable is the table that holds the project_issues relation/edge.
	ProjectIssuesTable = "project_issues"
	// ProjectIssuesInverseTable is the table name for the ProjectIssue entity.
	// It exists in this package in order to avoid circular dependency with the "projectissue" package.
	ProjectIssuesInverseTable = "project_issues"
	// ProjectIssuesColumn is the table column denoting the project_issues relation/edge.
	ProjectIssuesColumn = "user_id"
	// AssignedIssuesTable is the table that holds the assigned_issues relation/edge.
	AssignedIssuesTable = "project_issues"
	// AssignedIssuesInverseTable is the table name for the ProjectIssue entity.
	// It exists in this package in order to avoid circular dependency with the "projectissue" package.
	AssignedIssuesInverseTable = "project_issues"
	// AssignedIssuesColumn is the table column denoting the assigned_issues relation/edge.
	AssignedIssuesColumn = "assignee_id"
	// ProjectCollaboratorsTable is the table that holds the project_collaborators relation/edge.
	ProjectCollaboratorsTable = "project_collaborators"
	// ProjectCollaboratorsInverseTable is the table name for the ProjectCollaborator entity.
	// It exists in this package in order to avoid circular dependency with the "projectcollaborator" package.
	ProjectCollaboratorsInverseTable = "project_collaborators"
	// ProjectCollaboratorsColumn is the table column denoting the project_collaborators relation/edge.
	ProjectCollaboratorsColumn = "user_id"
	// ProjectIssueCommentsTable is the table that holds the project_issue_comments relation/edge.
	ProjectIssueCommentsTable = "project_issue_comments"
	// ProjectIssueCommentsInverseTable is the table name for the ProjectIssueComment entity.
	// It exists in this package in order to avoid circular dependency with the "projectissuecomment" package.
	ProjectIssueCommentsInverseTable = "project_issue_comments"
	// ProjectIssueCommentsColumn is the table column denoting the project_issue_comments relation/edge.
	ProjectIssueCommentsColumn = "user_id"
	// GitBotsTable is the table that holds the git_bots relation/edge. The primary key declared below.
	GitBotsTable = "git_bot_users"
	// GitBotsInverseTable is the table name for the GitBot entity.
	// It exists in this package in order to avoid circular dependency with the "gitbot" package.
	GitBotsInverseTable = "git_bots"
	// McpUpstreamsTable is the table that holds the mcp_upstreams relation/edge.
	McpUpstreamsTable = "mcp_upstreams"
	// McpUpstreamsInverseTable is the table name for the MCPUpstream entity.
	// It exists in this package in order to avoid circular dependency with the "mcpupstream" package.
	McpUpstreamsInverseTable = "mcp_upstreams"
	// McpUpstreamsColumn is the table column denoting the mcp_upstreams relation/edge.
	McpUpstreamsColumn = "user_id"
	// TeamMembersTable is the table that holds the team_members relation/edge.
	TeamMembersTable = "team_members"
	// TeamMembersInverseTable is the table name for the TeamMember entity.
	// It exists in this package in order to avoid circular dependency with the "teammember" package.
	TeamMembersInverseTable = "team_members"
	// TeamMembersColumn is the table column denoting the team_members relation/edge.
	TeamMembersColumn = "user_id"
	// TeamGroupMembersTable is the table that holds the team_group_members relation/edge.
	TeamGroupMembersTable = "team_group_members"
	// TeamGroupMembersInverseTable is the table name for the TeamGroupMember entity.
	// It exists in this package in order to avoid circular dependency with the "teamgroupmember" package.
	TeamGroupMembersInverseTable = "team_group_members"
	// TeamGroupMembersColumn is the table column denoting the team_group_members relation/edge.
	TeamGroupMembersColumn = "user_id"
	// GitBotUsersTable is the table that holds the git_bot_users relation/edge.
	GitBotUsersTable = "git_bot_users"
	// GitBotUsersInverseTable is the table name for the GitBotUser entity.
	// It exists in this package in order to avoid circular dependency with the "gitbotuser" package.
	GitBotUsersInverseTable = "git_bot_users"
	// GitBotUsersColumn is the table column denoting the git_bot_users relation/edge.
	GitBotUsersColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldName,
	FieldEmail,
	FieldAvatarURL,
	FieldPassword,
	FieldRole,
	FieldStatus,
	FieldIsBlocked,
	FieldDefaultConfigs,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TeamsPrimaryKey and TeamsColumn2 are the table columns denoting the
	// primary key for the teams relation (M2M).
	TeamsPrimaryKey = []string{"user_id", "team_id"}
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"user_id", "group_id"}
	// GitBotsPrimaryKey and GitBotsColumn2 are the table columns denoting the
	// primary key for the git_bots relation (M2M).
	GitBotsPrimaryKey = []string{"user_id", "git_bot_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/chaitin/MonkeyCode/backend/db/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsBlocked holds the default value on creation for the "is_blocked" field.
	DefaultIsBlocked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsBlocked orders the results by the is_blocked field.
func ByIsBlocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBlocked, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIdentitiesCount orders the results by identities count.
func ByIdentitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIdentitiesStep(), opts...)
	}
}

// ByIdentities orders the results by identities terms.
func ByIdentities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIdentitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuditsCount orders the results by audits count.
func ByAuditsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuditsStep(), opts...)
	}
}

// ByAudits orders the results by audits terms.
func ByAudits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamsCount orders the results by teams count.
func ByTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamsStep(), opts...)
	}
}

// ByTeams orders the results by teams terms.
func ByTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByModelsCount orders the results by models count.
func ByModelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newModelsStep(), opts...)
	}
}

// ByModels orders the results by models terms.
func ByModels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByImagesCount orders the results by images count.
func ByImagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImagesStep(), opts...)
	}
}

// ByImages orders the results by images terms.
func ByImages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHostsCount orders the results by hosts count.
func ByHostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHostsStep(), opts...)
	}
}

// ByHosts orders the results by hosts terms.
func ByHosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVmsCount orders the results by vms count.
func ByVmsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVmsStep(), opts...)
	}
}

// ByVms orders the results by vms terms.
func ByVms(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVmsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskModelSwitchesCount orders the results by task_model_switches count.
func ByTaskModelSwitchesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskModelSwitchesStep(), opts...)
	}
}

// ByTaskModelSwitches orders the results by task_model_switches terms.
func ByTaskModelSwitches(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskModelSwitchesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGitIdentitiesCount orders the results by git_identities count.
func ByGitIdentitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGitIdentitiesStep(), opts...)
	}
}

// ByGitIdentities orders the results by git_identities terms.
func ByGitIdentities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGitIdentitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectsCount orders the results by projects count.
func ByProjectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectsStep(), opts...)
	}
}

// ByProjects orders the results by projects terms.
func ByProjects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectIssuesCount orders the results by project_issues count.
func ByProjectIssuesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectIssuesStep(), opts...)
	}
}

// ByProjectIssues orders the results by project_issues terms.
func ByProjectIssues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectIssuesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssignedIssuesCount orders the results by assigned_issues count.
func ByAssignedIssuesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssignedIssuesStep(), opts...)
	}
}

// ByAssignedIssues orders the results by assigned_issues terms.
func ByAssignedIssues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedIssuesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectCollaboratorsCount orders the results by project_collaborators count.
func ByProjectCollaboratorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectCollaboratorsStep(), opts...)
	}
}

// ByProjectCollaborators orders the results by project_collaborators terms.
func ByProjectCollaborators(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectCollaboratorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectIssueCommentsCount orders the results by project_issue_comments count.
func ByProjectIssueCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectIssueCommentsStep(), opts...)
	}
}

// ByProjectIssueComments orders the results by project_issue_comments terms.
func ByProjectIssueComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectIssueCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGitBotsCount orders the results by git_bots count.
func ByGitBotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGitBotsStep(), opts...)
	}
}

// ByGitBots orders the results by git_bots terms.
func ByGitBots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGitBotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMcpUpstreamsCount orders the results by mcp_upstreams count.
func ByMcpUpstreamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMcpUpstreamsStep(), opts...)
	}
}

// ByMcpUpstreams orders the results by mcp_upstreams terms.
func ByMcpUpstreams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpUpstreamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamMembersCount orders the results by team_members count.
func ByTeamMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamMembersStep(), opts...)
	}
}

// ByTeamMembers orders the results by team_members terms.
func ByTeamMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamGroupMembersCount orders the results by team_group_members count.
func ByTeamGroupMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamGroupMembersStep(), opts...)
	}
}

// ByTeamGroupMembers orders the results by team_group_members terms.
func ByTeamGroupMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamGroupMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGitBotUsersCount orders the results by git_bot_users count.
func ByGitBotUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGitBotUsersStep(), opts...)
	}
}

// ByGitBotUsers orders the results by git_bot_users terms.
func ByGitBotUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGitBotUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newIdentitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IdentitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IdentitiesTable, IdentitiesColumn),
	)
}
func newAuditsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuditsTable, AuditsColumn),
	)
}
func newTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TeamsTable, TeamsPrimaryKey...),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
	)
}
func newModelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ModelsTable, ModelsColumn),
	)
}
func newImagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
	)
}
func newHostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HostsTable, HostsColumn),
	)
}
func newVmsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VmsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VmsTable, VmsColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
func newTaskModelSwitchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskModelSwitchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskModelSwitchesTable, TaskModelSwitchesColumn),
	)
}
func newGitIdentitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GitIdentitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GitIdentitiesTable, GitIdentitiesColumn),
	)
}
func newProjectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectsTable, ProjectsColumn),
	)
}
func newProjectIssuesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectIssuesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectIssuesTable, ProjectIssuesColumn),
	)
}
func newAssignedIssuesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedIssuesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssignedIssuesTable, AssignedIssuesColumn),
	)
}
func newProjectCollaboratorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectCollaboratorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectCollaboratorsTable, ProjectCollaboratorsColumn),
	)
}
func newProjectIssueCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectIssueCommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectIssueCommentsTable, ProjectIssueCommentsColumn),
	)
}
func newGitBotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GitBotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GitBotsTable, GitBotsPrimaryKey...),
	)
}
func newMcpUpstreamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpUpstreamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, McpUpstreamsTable, McpUpstreamsColumn),
	)
}
func newTeamMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamMembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TeamMembersTable, TeamMembersColumn),
	)
}
func newTeamGroupMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamGroupMembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupMembersTable, TeamGroupMembersColumn),
	)
}
func newGitBotUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GitBotUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, GitBotUsersTable, GitBotUsersColumn),
	)
}
