// Code generated by ent, DO NOT EDIT.

package gitbottask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldLTE(FieldID, id))
}

// GitBotID applies equality check predicate on the "git_bot_id" field. It's identical to GitBotIDEQ.
func GitBotID(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldGitBotID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldTaskID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldCreatedAt, v))
}

// GitBotIDEQ applies the EQ predicate on the "git_bot_id" field.
func GitBotIDEQ(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldGitBotID, v))
}

// GitBotIDNEQ applies the NEQ predicate on the "git_bot_id" field.
func GitBotIDNEQ(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNEQ(FieldGitBotID, v))
}

// GitBotIDIn applies the In predicate on the "git_bot_id" field.
func GitBotIDIn(vs ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldIn(FieldGitBotID, vs...))
}

// GitBotIDNotIn applies the NotIn predicate on the "git_bot_id" field.
func GitBotIDNotIn(vs ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNotIn(FieldGitBotID, vs...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNotIn(FieldTaskID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GitBotTask {
	return predicate.GitBotTask(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.GitBotTask {
	return predicate.GitBotTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.GitBotTask {
	return predicate.GitBotTask(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGitBot applies the HasEdge predicate on the "git_bot" edge.
func HasGitBot() predicate.GitBotTask {
	return predicate.GitBotTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GitBotTable, GitBotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGitBotWith applies the HasEdge predicate on the "git_bot" edge with a given conditions (other predicates).
func HasGitBotWith(preds ...predicate.GitBot) predicate.GitBotTask {
	return predicate.GitBotTask(func(s *sql.Selector) {
		step := newGitBotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GitBotTask) predicate.GitBotTask {
	return predicate.GitBotTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GitBotTask) predicate.GitBotTask {
	return predicate.GitBotTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GitBotTask) predicate.GitBotTask {
	return predicate.GitBotTask(sql.NotPredicates(p))
}
